Pin graphql-core in tests to < 3.2.7
The new version release Nov, 1st 2025 is currently causing TypeErrors in
a lot of tests:

    TypeError: Redefinition of reserved type 'ID'

Also expand the cheroot pin to <11 since they didn't fix the issue
before releasing 11.1.0.

Change-Id: Ibc90b47e36ceaf09f6e896f9f40391dd798300bb