Fix config check with current project include-vars
When checking if a change updates job config we did not properly account
for include-vars from the current project. In that case the include-vars
project is None and we must not attempt to resolve it via the layout.

ERROR [e: ...] Error freezing job graph for <QueueItem ... live for [<Change 0x... org/project2 1,1>] in check>
Traceback (most recent call last):
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/manager/__init__.py", line 1848, in prepareItem
    item.freezeJobGraph(self.getLayout(item),
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
                        self.current_context,
                        ^^^^^^^^^^^^^^^^^^^^^
                        skip_file_matcher=False,
                        ^^^^^^^^^^^^^^^^^^^^^^^^
                        redact_secrets_and_keys=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 7322, in freezeJobGraph
    results = layout.createJobGraph(context, self, skip_file_matcher,
                                    redact_secrets_and_keys)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 10985, in createJobGraph
    self.extendJobGraph(
    ~~~~~~~~~~~~~~~~~~~^
        context, item, change, ppc, job_graph, skip_file_matcher,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        redact_secrets_and_keys, debug_messages, pending_errors)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 10906, in extendJobGraph
    updates_job_config = item.updatesJobConfig(
        final_job, change, self)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 8276, in updatesJobConfig
    _, iv_project = layout.tenant.getProject(iv.project_name)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 11193, in getProject
    path = name.split('/', 1)
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Change-Id: I7a41008da05482ea0ea1e1831fa0ea307ef1d0a7