Fix provider node tag formatting
Use the dict with available format attributes directly instead of
creating an Attribute class, that currently leads to the following
exception:

    zuul.AwsProvider: Error formatting metadata MicroserviceName
    Traceback (most recent call last):
      File "/opt/zuul/lib/python3.13/site-packages/zuul/provider/__init__.py", line 548, in getNodeTags
        tags[k] = v.format(**attributes)
                  ~~~~~~~~^^^^^^^^^^^^^^
    TypeError: str.format() argument after ** must be a mapping, not Attributes

Change-Id: Idc2559e2fe10def6824e09fe7004d9e545771440