Fix test shutdown race in test_max_ready_age
As test_max_ready_age finishes and cleans up after itself it is possible
for the launcher to be attempting to boot additional servers (due to
anywhere from 3-5 min ready being valid) which raise exceptions if the
threadpool (and probably other resources) are shutdown. This leads to
logs like this:

  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/launcher/server.py", line 1561, in _processNodes
      self._checkNode(node, log)
      ~~~~~~~~~~~~~~~^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/launcher/server.py", line 1690, in _checkNode
      instance = node.create_state_machine.advance()
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/aws/awsendpoint.py", line 235, in advance
      self.create_future = self.endpoint._submitCreateInstance(
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
          self.provider, self.label, self.flavor, self.image,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          self.image_external_id, self.tags, self.hostname,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          self.node.aws_dedicated_host_id, self.log)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/aws/awsendpoint.py", line 1514, in _submitCreateInstance
      return self.create_executor.submit(
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
          self._createInstance,
          ^^^^^^^^^^^^^^^^^^^^^
          provider, label, flavor, image, image_external_id,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          tags, hostname, dedicated_host_id, log)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 171, in submit
      raise RuntimeError('cannot schedule new futures after shutdown')
  RuntimeError: cannot schedule new futures after shutdown
  2025-07-30 23:40:30,601 zuul.Launcher                    DEBUG    Stopped launcher
  2025-07-30 23:40:30,601 zuul.Launcher                    DEBUG    Joining launcher

The test then fails due to unexpected exceptions. Since we're testing
the launcher is operating correctly here we don't want to mask this
error off in case it happens during runtime somehow. Instead at the end
of the test we reconfigure the launcher to remove all min-ready nodes
and wait for the launcher config to sync up. This should prevent it from
attempting to start any new node launches as components shutdown.

Change-Id: Ida18f3c84fad3ae1ffd8699fffe678c94430f3f6