Don't delete uploads w/o active endpoint
When checking old images we need to ignore uploads that we don't have an
active endpoint for.

Currently this leads to the following exception:

ERROR zuul.Launcher: Unable to delete upload <ImageUpload e6336336dc6c483992d59ebe3664b616 state: ...>
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.13/site-packages/zuul/launcher/server.py", line 153, in _run
    provider.deleteImage(self.upload.external_id)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/driver/aws/awsprovider.py", line 440, in deleteImage
    self.endpoint.deleteImage(external_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/driver/aws/awsendpoint.py", line 1271, in deleteImage
    for ami in self._listAmis():
               ~~~~~~~~~~~~~~^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/driver/aws/awsendpoint.py", line 1630, in _listAmis
    paginator = self.ec2_client.get_paginator('describe_images')
                ^^^^^^^^^^^^^^^
AttributeError: 'AwsProviderEndpoint' object has no attribute 'ec2_client'. Did you mean: 'zk_client'?

Change-Id: I9d924b9ad5697776459b4ffdd42ad47992028c59