Raise minimum required boto3 version to support Nested Virtualization
The support for nested virtualization starts with boto3 version 1.42.48
[1]. Running the Zuul unit tests with a lower version, results in the
following exception for tests using nested virtualization:

Traceback (most recent call last):
  File "/workspace/zuul/launcher/server.py", line 1913, in _processProviderNode
    self._checkNodeCreate(node, log)
  File "/workspace/zuul/launcher/server.py", line 2143, in _checkNodeCreate
    instance = node.create_state_machine.advance()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/zuul/driver/aws/awsendpoint.py", line 256, in advance
    instance = self.endpoint._completeCreateInstance(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/zuul/driver/aws/awsendpoint.py", line 1930, in _completeCreateInstance
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/zuul/driver/aws/awsendpoint.py", line 1957, in _createInstance
    return self._runInstance(label, flavor, image_id, tags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/zuul/driver/aws/awsendpoint.py", line 2334, in _runInstance
    resp = self.ec2_client.run_instances(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tests/fake_aws.py", line 254, in _fake_run_instances
    return self.ec2_client.run_instances_orig(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 602, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1035, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1102, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in CpuOptions: "NestedVirtualization", must be one of: CoreCount, ThreadsPerCore, AmdSevSnp

[1]: https://github.com/boto/botocore/blame/3ed8b67d92927698b9e9561f2ed95a7d6291fd35/CHANGELOG.rst#L501

Change-Id: I86ca02e640fe1cc44ed41b5a5c2e9321afe423b1