Prevent error in stats to stop pipeline processing
When there is an exception emitting stats for a node request, this will
cause the pipeline processing to be aborted.

In one particular case this was due to a non-ascii character in a label.

In addition to handling that exception we will also make sure to
normalize the request labels and replace all non-ascii chars.

ERROR zuul.Scheduler: Exception in pipeline processing:
Traceback (most recent call last):
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/scheduler.py"", line 2453, in _process_pipeline
    while not self._stopped and manager.processQueue(
                                ~~~~~~~~~~~~~~~~~~~~^
            tenant_lock):
            ^^^^^^^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/manager/__init__.py"", line 2078, in processQueue
    item_changed, nnfi = self._processOneItem(
                         ~~~~~~~~~~~~~~~~~~~~^
        item, nnfi)
        ^^^^^^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/manager/__init__.py"", line 1959, in _processOneItem
    if ready and self.provisionNodes(item):
                 ~~~~~~~~~~~~~~~~~~~^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/manager/__init__.py"", line 1192, in provisionNodes
    self._makeNodepoolRequest(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        log, build_set, job, relative_priority)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/manager/__init__.py"", line 1216, in _makeNodepoolRequest
    req = self.sched.nodepool.requestNodes(
        build_set.uuid, job, tenant_name, pipeline_name, provider,
        priority, relative_priority, event=item.event)
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/nodepool.py"", line 201, in requestNodes
    self.emitStats(req)
    ~~~~~~~~~~~~~~^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/zuul/nodepool.py"", line 169, in emitStats
    pipe.send()
    ~~~~~~~~~^^
  File ""/opt/zuul/lib/python3.13/site-packages/statsd/client/base.py"", line 102, in send
    self._send()
    ~~~~~~~~~~^^
  File ""/opt/zuul/lib/python3.13/site-packages/statsd/client/udp.py"", line 22, in _send
    self._client._after(data)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/statsd/client/base.py"", line 76, in _after
    self._send(data)
    ~~~~~~~~~~^^^^^^
  File ""/opt/zuul/lib/python3.13/site-packages/statsd/client/udp.py"", line 42, in _send
    self._sock.sendto(data.encode('ascii'), self._addr)
                      ~~~~~~~~~~~^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 156: ordinal not in range(128)"

Change-Id: Id1db2aa706e5ec235443e7abdba296c83bcade81