Don't return a cache key for item subnodes
During cache init we might get init and watch events interleaved, which
can cause the playback worker processing events for which there is no
object in the cache yet.

Since we returned a cache key from `parsePath()` also for subnodes, we
could end up with the following traceback where the cache attempts to
create a cache object with object subnode data:

ERROR zuul.zk.ZooKeeper: Error playing back event WatchedEvent(type='CREATED', state='CONNECTED', path='/zuul/nodes/nodes/9917c9b9e30748048e83e7fb355dff3a/assignment', zxid=798972170883):
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/zkobject.py", line 740, in _fromRaw
    klass = cls._subclasses[subclass_id]
            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: b'x\x9c5\xcb1\x0e\x80 \x0c'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/cache.py", line 314, in _playbackWorker
    self._handlePlayback(event, future, key)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/cache.py", line 392, in _handlePlayback
    obj = self.objectFromRaw(key, data, stat)
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/launcher.py", line 140, in objectFromRaw
    return self.zkobject_class._fromRaw(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._zk_context, data, zstat, None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/zkobject.py", line 742, in _fromRaw
    raise RuntimeError(f"Unknown subclass id: {subclass_id}")
RuntimeError: Unknown subclass id: b'x\x9c5\xcb1\x0e\x80 \x0c'

Fix this by only returning a cache key when we are handling an event for
the cached object (or a shard of it).

Change-Id: I5137f8a27c775c78d8726d39f2eccbf6c5c8c8b1