Fix branch-cache compat mode issue
The change to use per-project branch caches has an error when running
in the backwards compatible mode for model api 36.  If we receive a
branch deleted or created event, we will set the min_ltime to None
(because the old version of the branch cache methods used were not
updated to return an ltime; they return None).

To correct this:

* Update the old version of the branch cache to return the ltime
* Make the default value handling robust against similar errors
* Warn on and ignore invalid ltime values
* Add tests for creating and deleting branches on model 36 in
  backwards compat mode

This is a traceback from the error seen when deleting a branch

ERROR zuul.Scheduler: [e: ...] Unable to forward event <GithubTriggerEvent 0x7ff34599c050 push org/repo refs/heads/foobar branch_deleted github/org/repo delivery: ...> to tenant tenant-one
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.13/site-packages/zuul/scheduler.py", line 2592, in process_tenant_trigger_queue
    self._forward_trigger_event(event, tenant)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/scheduler.py", line 2641, in _forward_trigger_event
    elif (event.branch in project.source.getProjectBranches(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
            project, tenant, min_ltime=event.branch_cache_ltime)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/driver/github/githubsource.py", line 140, in getProjectBranches
    return self.connection.getProjectBranches(project, tenant, min_ltime)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.13/site-packages/zuul/connection/__init__.py", line 327, in getProjectBranches
    branches = self._branch_cache.getProjectBranches(
        project.name, required_flags, min_ltime)
  File "/opt/zuul/lib/python3.13/site-packages/zuul/zk/branch_cache.py", line 281, in getProjectBranches
    if self.ltime < min_ltime:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'NoneType'

Change-Id: I610b8e3006e48e6c3d3883751f01308e17373895
Co-Authored-By: James E. Blair <jim@acmegating.com>