Pin graphql-core in tests to < 3.2.7
The new version release Nov, 1st 2025 is currently causing TypeErrors in
a lot of tests:

    TypeError: Redefinition of reserved type 'ID'

Change-Id: Ibc90b47e36ceaf09f6e896f9f40391dd798300bb