Stop executor api instances in unittests
Tests like test_lost_build_requests have failed with this log:

  ft1.1: tests.unit.test_zk.TestExecutorApi.test_lost_build_requeststesttools.testresult.real._StringException: logging: {{{
  2025-03-28 01:32:22,207 zuul.zk.base.ZooKeeperClient     DEBUG    ZooKeeper connection (session: 0x100005c5e5327e8): CONNECTED
  2025-03-28 01:32:22,246 zuul.ComponentRegistry           INFO     System minimum data model version 33; this component 33
  2025-03-28 01:32:22,262 zuul.ComponentRegistry           INFO     System minimum data model version 33; this component 33
  2025-03-28 01:32:22,263 zuul.ExecutorQueue               DEBUG    Creating executor queue at root /zuul/executor/unzoned
  2025-03-28 01:32:22,291 zuul.zk.ZooKeeper                DEBUG    Initialize cache at /zuul/executor/unzoned
  2025-03-28 01:32:22,308 zuul.zk.ZooKeeper                DEBUG    Cache at /zuul/executor/unzoned is ready
  2025-03-28 01:32:22,308 zuul.ExecutorQueue               DEBUG    Creating executor queue at root /zuul/executor/zones/zone
  2025-03-28 01:32:22,335 zuul.zk.ZooKeeper                DEBUG    Initialize cache at /zuul/executor/zones/zone
  2025-03-28 01:32:22,354 zuul.zk.ZooKeeper                DEBUG    Cache at /zuul/executor/zones/zone is ready
  2025-03-28 01:32:22,354 zuul.ExecutorQueue               DEBUG    [e: pipeline] Submitting job request to ZooKeeper <BuildRequest A, job=job, state=requested, path=/zuul/executor/zones/zone/requests/A zone=zone>
  2025-03-28 01:32:22,370 zuul.ExecutorQueue               DEBUG    [e: pipeline] Submitting job request to ZooKeeper <BuildRequest B, job=job, state=requested, path=/zuul/executor/unzoned/requests/B zone=None>
  2025-03-28 01:32:22,384 zuul.ExecutorQueue               DEBUG    [e: pipeline] Submitting job request to ZooKeeper <BuildRequest C, job=job, state=requested, path=/zuul/executor/zones/zone/requests/C zone=zone>
  2025-03-28 01:32:22,395 zuul.ExecutorQueue               DEBUG    [e: pipeline] Submitting job request to ZooKeeper <BuildRequest D, job=job, state=requested, path=/zuul/executor/zones/zone/requests/D zone=zone>
  2025-03-28 01:32:22,405 zuul.ExecutorQueue               DEBUG    [e: pipeline] Submitting job request to ZooKeeper <BuildRequest E, job=job, state=requested, path=/zuul/executor/zones/zone/requests/E zone=zone>
  2025-03-28 01:32:22,419 zuul.JobRequestQueue             DEBUG    [e: pipeline] [build: B] Updating request <BuildRequest B, job=job, state=running, path=/zuul/executor/unzoned/requests/B zone=None>
  2025-03-28 01:32:22,429 zuul.JobRequestQueue             DEBUG    [e: pipeline] [build: C] Updating request <BuildRequest C, job=job, state=requested, path=/zuul/executor/zones/zone/requests/C zone=zone>
  2025-03-28 01:32:22,431 zuul.JobRequestQueue             DEBUG    [e: pipeline] [build: D] Updating request <BuildRequest D, job=job, state=completed, path=/zuul/executor/zones/zone/requests/D zone=zone>
  2025-03-28 01:32:22,433 zuul.JobRequestQueue             DEBUG    [e: pipeline] [build: E] Updating request <BuildRequest E, job=job, state=paused, path=/zuul/executor/zones/zone/requests/E zone=zone>
  2025-03-28 01:32:22,441 zuul.zk.base.ZooKeeperClient     DEBUG    ZooKeeper connection (session: 0x0): LOST
  2025-03-28 01:32:22,442 zuul.zk.ZooKeeper                ERROR    Error playing back event WatchedEvent(type='CHANGED', state='CONNECTED', path='/zuul/executor/zones/zone/requests/E'):
  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/cache.py", line 279, in _playbackWorker
      self._handlePlayback(event, future, key)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/cache.py", line 291, in _handlePlayback
      data, stat = future.get()
                   ^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/.nox/tests-3-11/lib/python3.11/site-packages/kazoo/handlers/utils.py", line 86, in get
      raise self._exception
  kazoo.exceptions.ConnectionLoss
  }}}

  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/tests/base.py", line 1888, in checkLogs
      self.fail(f"Traceback found in logs: {record.msg}")
    File "/usr/lib/python3.11/unittest/case.py", line 703, in fail
      raise self.failureException(msg)
  AssertionError: Traceback found in logs: Error playing back event %s:

This is a relatively short and quick test and the zookeeper shutdown
appears intentional at the end of our test. I think what is happening is
our normal test shutdown process disconnects self.zk_client.
Unfortunately, in these ExecutorAPI tests we've also passed this
self.zk_client instance into the ExecutorAPI where it is used by caches
which have watches. These watches then notice the disconnect and attempt
to replay state and break.

Fix this in the tests by explicitly stopping each created ExecutorAPI
which stops the caches.

Change-Id: I424ca44e2894ef94b7fdf5c191bc630833d649bc