Iterate static dict values in estimateDataSize
At least one test case has failed because runStats() raised and
exception originating in estimateDataSize:

  2025-07-30 23:34:24,085 zuul.Scheduler-0                 ERROR    Error in periodic stats:
  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 480, in runStats
      self._runStats()
      ~~~~~~~~~~~~~~^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 632, in _runStats
      manager.state.estimateDataSize()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 344, in estimateDataSize
      c, u = walk(self.__dict__)
             ~~~~^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 333, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 339, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 329, in walk
      compressed, uncompressed = obj.estimateDataSize(seen)
                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 344, in estimateDataSize
      c, u = walk(self.__dict__)
             ~~~~^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 333, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 339, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 329, in walk
      compressed, uncompressed = obj.estimateDataSize(seen)
                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 344, in estimateDataSize
      c, u = walk(self.__dict__)
             ~~~~^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 333, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 329, in walk
      compressed, uncompressed = obj.estimateDataSize(seen)
                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 344, in estimateDataSize
      c, u = walk(self.__dict__)
             ~~~~^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 333, in walk
      c, u = walk(sub)
             ~~~~^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/zk/zkobject.py", line 332, in walk
      for sub in obj.values():
                 ~~~~~~~~~~^^
  RuntimeError: dictionary changed size during iteration

As we walk through dict objects we iterated over their values() which is
a dict_values iterator that is a live view on the dictionary. If the
pipeline state changes while we runStats() it is reasonable that these
dictionairies would change resulting in this error. Fix this by
iterating through a static list of values through an explicit type
coercion to list().

This might hang onto memory that we were otherwise garbage collecting
for a little bit longer, but once we're done running stats we should be
able to free the memory. Considering this is an estimate using a
snapshot in time seems reasonable.

Change-Id: I23649fae8cb4064518ba19d12e67fac3e5605a8a